import { Product, Category } from '../types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'T-Shirts', slug: 'tshirts', description: 'Premium tees', image_url: 'https://images.pexels.com/photos/1656684/pexels-photo-1656684.jpeg?auto=compress&cs=tinysrgb&w=400', created_at: '' },
  { id: 'cat-2', name: 'Shirts', slug: 'shirts', description: 'Formal & casual', image_url: 'https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg?auto=compress&cs=tinysrgb&w=400', created_at: '' },
  { id: 'cat-3', name: 'Hoodies', slug: 'hoodies', description: 'Cozy hoodies', image_url: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=400', created_at: '' },
  { id: 'cat-4', name: 'Trousers', slug: 'trousers', description: 'Slim & regular fit', image_url: 'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=400', created_at: '' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p-001', code: 'LL-TS-001', name: 'Classic White Essential Tee',
    description: 'Our signature premium cotton t-shirt. Crafted from 100% ring-spun cotton for an exceptionally soft feel. The perfect wardrobe staple.',
    price: 799, original_price: 1299, category_id: 'cat-1', brand: 'LordLook',
    tags: ['bestseller', 'casual', 'cotton'],
    colors: [
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Black', hex: '#1A1A1A' },
      { name: 'Navy', hex: '#1E3A5F' },
      { name: 'Olive', hex: '#556B2F' },
    ],
    keywords: ['white tshirt', 'basic tee', 'cotton tshirt', 'essential tee', 'plain tshirt', 'everyday wear'],
    is_trending: true, is_featured: true, is_active: true,
    rating_avg: 4.5, rating_count: 128, created_at: '', updated_at: '',
    product_images: [
      { id: 'img-1', product_id: 'p-001', url: 'https://images.pexels.com/photos/1656684/pexels-photo-1656684.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Classic White Tee', sort_order: 0 },
      { id: 'img-2', product_id: 'p-001', url: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Classic White Tee back', sort_order: 1 },
      { id: 'img-3', product_id: 'p-001', url: 'https://images.pexels.com/photos/1021693/pexels-photo-1021693.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Classic White Tee detail', sort_order: 2 },
      { id: 'img-4', product_id: 'p-001', url: 'https://images.pexels.com/photos/1192609/pexels-photo-1192609.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Classic White Tee lifestyle', sort_order: 3 },
    ],
    product_sizes: [
      { id: 's1', product_id: 'p-001', size: 'S', stock: 15 },
      { id: 's2', product_id: 'p-001', size: 'M', stock: 20 },
      { id: 's3', product_id: 'p-001', size: 'L', stock: 18 },
      { id: 's4', product_id: 'p-001', size: 'XL', stock: 10 },
      { id: 's5', product_id: 'p-001', size: 'XXL', stock: 5 },
    ],
  },
  {
    id: 'p-002', code: 'LL-SH-002', name: 'Oxford Slim-Fit Shirt',
    description: 'A modern take on the classic Oxford shirt. Tailored slim fit with fine cotton poplin fabric. Ideal for smart-casual occasions.',
    price: 1599, original_price: 2499, category_id: 'cat-2', brand: 'LordLook',
    tags: ['formal', 'slim-fit', 'oxford'],
    colors: [
      { name: 'Light Blue', hex: '#B0C4DE' },
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Pink', hex: '#F4C2C2' },
    ],
    keywords: ['oxford shirt', 'formal shirt', 'office wear', 'slim fit shirt', 'dress shirt', 'business casual'],
    is_trending: true, is_featured: false, is_active: true,
    rating_avg: 4.7, rating_count: 89, created_at: '', updated_at: '',
    product_images: [
      { id: 'img-5', product_id: 'p-002', url: 'https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Oxford Shirt front', sort_order: 0 },
      { id: 'img-6', product_id: 'p-002', url: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Oxford Shirt styled', sort_order: 1 },
      { id: 'img-7', product_id: 'p-002', url: 'https://images.pexels.com/photos/2897531/pexels-photo-2897531.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Oxford Shirt close', sort_order: 2 },
      { id: 'img-8', product_id: 'p-002', url: 'https://images.pexels.com/photos/1852759/pexels-photo-1852759.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Oxford Shirt back', sort_order: 3 },
    ],
    product_sizes: [
      { id: 's6', product_id: 'p-002', size: 'S', stock: 8 },
      { id: 's7', product_id: 'p-002', size: 'M', stock: 12 },
      { id: 's8', product_id: 'p-002', size: 'L', stock: 14 },
      { id: 's9', product_id: 'p-002', size: 'XL', stock: 7 },
    ],
  },
  {
    id: 'p-003', code: 'LL-HD-003', name: 'Premium Fleece Hoodie',
    description: 'Plush 300GSM fleece hoodie with a kangaroo pocket and adjustable drawstring. Built for comfort through every season.',
    price: 2199, original_price: 3499, category_id: 'cat-3', brand: 'LordLook',
    tags: ['hoodie', 'fleece', 'winter'],
    colors: [
      { name: 'Charcoal', hex: '#36454F' },
      { name: 'Black', hex: '#1A1A1A' },
      { name: 'Heather Grey', hex: '#B6B6B6' },
      { name: 'Forest Green', hex: '#228B22' },
    ],
    keywords: ['fleece hoodie', 'warm hoodie', 'winter wear', 'pullover', 'hooded sweatshirt', 'cozy hoodie'],
    is_trending: false, is_featured: true, is_active: true,
    rating_avg: 4.8, rating_count: 214, created_at: '', updated_at: '',
    product_images: [
      { id: 'img-9', product_id: 'p-003', url: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Hoodie front', sort_order: 0 },
      { id: 'img-10', product_id: 'p-003', url: 'https://images.pexels.com/photos/1021693/pexels-photo-1021693.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Hoodie back', sort_order: 1 },
      { id: 'img-11', product_id: 'p-003', url: 'https://images.pexels.com/photos/1462637/pexels-photo-1462637.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Hoodie detail', sort_order: 2 },
      { id: 'img-12', product_id: 'p-003', url: 'https://images.pexels.com/photos/2220316/pexels-photo-2220316.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Hoodie lifestyle', sort_order: 3 },
    ],
    product_sizes: [
      { id: 's10', product_id: 'p-003', size: 'S', stock: 6 },
      { id: 's11', product_id: 'p-003', size: 'M', stock: 9 },
      { id: 's12', product_id: 'p-003', size: 'L', stock: 11 },
      { id: 's13', product_id: 'p-003', size: 'XL', stock: 8 },
      { id: 's14', product_id: 'p-003', size: 'XXL', stock: 4 },
    ],
  },
  {
    id: 'p-004', code: 'LL-TR-004', name: 'Slim Chino Trousers',
    description: 'Versatile slim-fit chinos made from stretch cotton. Comfortable for all-day wear with a refined silhouette.',
    price: 1899, original_price: 2999, category_id: 'cat-4', brand: 'LordLook',
    tags: ['chino', 'casual', 'slim'],
    colors: [
      { name: 'Beige', hex: '#F5F5DC' },
      { name: 'Khaki', hex: '#C3B091' },
      { name: 'Navy', hex: '#1E3A5F' },
      { name: 'Olive', hex: '#556B2F' },
    ],
    keywords: ['chino pants', 'slim trousers', 'casual pants', 'stretch chinos', 'office pants', 'formal trousers'],
    is_trending: true, is_featured: false, is_active: true,
    rating_avg: 4.4, rating_count: 67, created_at: '', updated_at: '',
    product_images: [
      { id: 'img-13', product_id: 'p-004', url: 'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Chino Trousers', sort_order: 0 },
      { id: 'img-14', product_id: 'p-004', url: 'https://images.pexels.com/photos/1598508/pexels-photo-1598508.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Chino detail', sort_order: 1 },
      { id: 'img-15', product_id: 'p-004', url: 'https://images.pexels.com/photos/914668/pexels-photo-914668.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Chino styled', sort_order: 2 },
      { id: 'img-16', product_id: 'p-004', url: 'https://images.pexels.com/photos/1192609/pexels-photo-1192609.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Chino lifestyle', sort_order: 3 },
    ],
    product_sizes: [
      { id: 's15', product_id: 'p-004', size: 'S', stock: 7 },
      { id: 's16', product_id: 'p-004', size: 'M', stock: 13 },
      { id: 's17', product_id: 'p-004', size: 'L', stock: 10 },
      { id: 's18', product_id: 'p-004', size: 'XL', stock: 6 },
    ],
  },
  {
    id: 'p-005', code: 'LL-TS-005', name: 'Graphic Street Tee',
    description: 'Bold street-art inspired graphic print on heavy 220GSM cotton. A statement piece for the fashion-forward individual.',
    price: 999, original_price: 1599, category_id: 'cat-1', brand: 'LordLook',
    tags: ['graphic', 'streetwear', 'bold'],
    colors: [
      { name: 'Black', hex: '#1A1A1A' },
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Red', hex: '#CC2936' },
    ],
    keywords: ['graphic tee', 'streetwear', 'printed tshirt', 'bold print', 'urban fashion', 'statement tee'],
    is_trending: true, is_featured: true, is_active: true,
    rating_avg: 4.3, rating_count: 156, created_at: '', updated_at: '',
    product_images: [
      { id: 'img-17', product_id: 'p-005', url: 'https://images.pexels.com/photos/1021693/pexels-photo-1021693.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Graphic Tee front', sort_order: 0 },
      { id: 'img-18', product_id: 'p-005', url: 'https://images.pexels.com/photos/1656684/pexels-photo-1656684.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Graphic Tee back', sort_order: 1 },
      { id: 'img-19', product_id: 'p-005', url: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Graphic Tee detail', sort_order: 2 },
      { id: 'img-20', product_id: 'p-005', url: 'https://images.pexels.com/photos/1192609/pexels-photo-1192609.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Graphic Tee styled', sort_order: 3 },
    ],
    product_sizes: [
      { id: 's19', product_id: 'p-005', size: 'XS', stock: 5 },
      { id: 's20', product_id: 'p-005', size: 'S', stock: 12 },
      { id: 's21', product_id: 'p-005', size: 'M', stock: 18 },
      { id: 's22', product_id: 'p-005', size: 'L', stock: 15 },
      { id: 's23', product_id: 'p-005', size: 'XL', stock: 9 },
    ],
  },
  {
    id: 'p-006', code: 'LL-SH-006', name: 'Linen Summer Shirt',
    description: 'Lightweight and breathable linen shirt perfect for warm weather. Features a relaxed fit and mother-of-pearl buttons.',
    price: 1399, original_price: 2199, category_id: 'cat-2', brand: 'LordLook',
    tags: ['linen', 'summer', 'casual'],
    colors: [
      { name: 'Sky Blue', hex: '#87CEEB' },
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Sand', hex: '#C2B280' },
      { name: 'Sage', hex: '#9DC183' },
    ],
    keywords: ['linen shirt', 'summer shirt', 'breathable shirt', 'vacation wear', 'beach shirt', 'lightweight shirt'],
    is_trending: false, is_featured: true, is_active: true,
    rating_avg: 4.6, rating_count: 43, created_at: '', updated_at: '',
    product_images: [
      { id: 'img-21', product_id: 'p-006', url: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Linen Shirt front', sort_order: 0 },
      { id: 'img-22', product_id: 'p-006', url: 'https://images.pexels.com/photos/2897531/pexels-photo-2897531.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Linen Shirt detail', sort_order: 1 },
      { id: 'img-23', product_id: 'p-006', url: 'https://images.pexels.com/photos/1852759/pexels-photo-1852759.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Linen Shirt styled', sort_order: 2 },
      { id: 'img-24', product_id: 'p-006', url: 'https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Linen Shirt back', sort_order: 3 },
    ],
    product_sizes: [
      { id: 's24', product_id: 'p-006', size: 'S', stock: 4 },
      { id: 's25', product_id: 'p-006', size: 'M', stock: 9 },
      { id: 's26', product_id: 'p-006', size: 'L', stock: 7 },
      { id: 's27', product_id: 'p-006', size: 'XL', stock: 5 },
    ],
  },
  {
    id: 'p-007', code: 'LL-HD-007', name: 'Zip-Up Track Hoodie',
    description: 'Athletic zip-up hoodie with moisture-wicking inner lining. Perfect for gym sessions or casual streetwear.',
    price: 1799, original_price: 2799, category_id: 'cat-3', brand: 'LordLook',
    tags: ['athletic', 'zip', 'sport'],
    colors: [
      { name: 'Black', hex: '#1A1A1A' },
      { name: 'Grey', hex: '#808080' },
      { name: 'Navy', hex: '#1E3A5F' },
    ],
    keywords: ['zip hoodie', 'athletic hoodie', 'gym wear', 'track hoodie', 'sportswear', 'zip up sweatshirt'],
    is_trending: true, is_featured: false, is_active: true,
    rating_avg: 4.2, rating_count: 91, created_at: '', updated_at: '',
    product_images: [
      { id: 'img-25', product_id: 'p-007', url: 'https://images.pexels.com/photos/1462637/pexels-photo-1462637.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Track Hoodie front', sort_order: 0 },
      { id: 'img-26', product_id: 'p-007', url: 'https://images.pexels.com/photos/2220316/pexels-photo-2220316.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Track Hoodie back', sort_order: 1 },
      { id: 'img-27', product_id: 'p-007', url: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Track Hoodie detail', sort_order: 2 },
      { id: 'img-28', product_id: 'p-007', url: 'https://images.pexels.com/photos/1021693/pexels-photo-1021693.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Track Hoodie lifestyle', sort_order: 3 },
    ],
    product_sizes: [
      { id: 's28', product_id: 'p-007', size: 'S', stock: 5 },
      { id: 's29', product_id: 'p-007', size: 'M', stock: 8 },
      { id: 's30', product_id: 'p-007', size: 'L', stock: 12 },
      { id: 's31', product_id: 'p-007', size: 'XL', stock: 7 },
      { id: 's32', product_id: 'p-007', size: 'XXL', stock: 3 },
    ],
  },
  {
    id: 'p-008', code: 'LL-TR-008', name: 'Cargo Combat Trousers',
    description: 'Durable multi-pocket cargo trousers crafted from ripstop fabric. Utility meets style in this essential wardrobe piece.',
    price: 2299, original_price: 3499, category_id: 'cat-4', brand: 'LordLook',
    tags: ['cargo', 'utility', 'streetwear'],
    colors: [
      { name: 'Olive', hex: '#556B2F' },
      { name: 'Black', hex: '#1A1A1A' },
      { name: 'Khaki', hex: '#C3B091' },
      { name: 'Camel', hex: '#C19A6B' },
    ],
    keywords: ['cargo pants', 'combat trousers', 'utility pants', 'multi pocket', 'streetwear pants', 'ripstop trousers'],
    is_trending: false, is_featured: true, is_active: true,
    rating_avg: 4.6, rating_count: 77, created_at: '', updated_at: '',
    product_images: [
      { id: 'img-29', product_id: 'p-008', url: 'https://images.pexels.com/photos/914668/pexels-photo-914668.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Cargo Trousers front', sort_order: 0 },
      { id: 'img-30', product_id: 'p-008', url: 'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Cargo Trousers pocket', sort_order: 1 },
      { id: 'img-31', product_id: 'p-008', url: 'https://images.pexels.com/photos/1598508/pexels-photo-1598508.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Cargo Trousers back', sort_order: 2 },
      { id: 'img-32', product_id: 'p-008', url: 'https://images.pexels.com/photos/1192609/pexels-photo-1192609.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Cargo Trousers lifestyle', sort_order: 3 },
    ],
    product_sizes: [
      { id: 's33', product_id: 'p-008', size: 'S', stock: 6 },
      { id: 's34', product_id: 'p-008', size: 'M', stock: 10 },
      { id: 's35', product_id: 'p-008', size: 'L', stock: 8 },
      { id: 's36', product_id: 'p-008', size: 'XL', stock: 5 },
    ],
  },
];

export const ALL_COLORS = [
  { name: 'White', hex: '#FFFFFF' },
  { name: 'Black', hex: '#1A1A1A' },
  { name: 'Navy', hex: '#1E3A5F' },
  { name: 'Olive', hex: '#556B2F' },
  { name: 'Charcoal', hex: '#36454F' },
  { name: 'Grey', hex: '#808080' },
  { name: 'Beige', hex: '#F5F5DC' },
  { name: 'Khaki', hex: '#C3B091' },
  { name: 'Red', hex: '#CC2936' },
  { name: 'Light Blue', hex: '#B0C4DE' },
  { name: 'Pink', hex: '#F4C2C2' },
  { name: 'Sky Blue', hex: '#87CEEB' },
  { name: 'Sand', hex: '#C2B280' },
  { name: 'Sage', hex: '#9DC183' },
  { name: 'Forest Green', hex: '#228B22' },
  { name: 'Heather Grey', hex: '#B6B6B6' },
  { name: 'Camel', hex: '#C19A6B' },
];

export const SEARCH_SUGGESTIONS = [
  'Classic White Essential Tee',
  'Premium Fleece Hoodie',
  'Oxford Slim-Fit Shirt',
];

export const MOCK_COUPONS: Record<string, { discount_type: 'percentage' | 'fixed'; discount_value: number; min_order_amount: number; max_discount: number; description: string }> = {
  'LORDLOOK10': { discount_type: 'percentage', discount_value: 10, min_order_amount: 999, max_discount: 500, description: '10% off on orders above ₹999' },
  'WELCOME20': { discount_type: 'percentage', discount_value: 20, min_order_amount: 1499, max_discount: 800, description: '20% off for new customers' },
  'FLAT200': { discount_type: 'fixed', discount_value: 200, min_order_amount: 1999, max_discount: 200, description: '₹200 flat off on orders above ₹1999' },
  'SUMMER15': { discount_type: 'percentage', discount_value: 15, min_order_amount: 1299, max_discount: 600, description: '15% summer discount' },
};
